channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - matplotlib=3.3.3
  - pip:
    - z3-solver==4.8.10.0
    - plotly== 4.14.3
    - pandas== 1.2.3
    - kaleido== 0.2.1
    - -e .
